### PR TITLE
fix: preallocate maps

### PR DESCRIPTION
**Pull request by cristaloleg**

### CODE REVIEW

**Comment by janisz** [comment]
It will be cool if we can add benchmark to show this change actually improved performance.

**Comment by cristaloleg** [comment]
ok, will do this

**Comment by cristaloleg** [comment]
Changes are quite neglectable, it's used in cold paths.
Merge it or not is your decision 😉

**Comment by mjarco** [comment]
LGTM. I'll merge after running some more tests. Thanks!

**Pull request merged**
